Request to /clothes/6/ took 0.02 seconds, Method: GET, Status Code: 200
Request to / took 0.05 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /register/
Request to /register/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /register/
Request to /register/ took 0.05 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.01 seconds, Method: GET, Status Code: 200
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 19, in post
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 161, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 155, in _create_user
    user.save(using=self._db)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: auth_user
Request to /register/ took 0.46 seconds, Method: POST, Status Code: 500
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.01 seconds, Method: GET, Status Code: 200
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 26, in post
    return redirect('main_view')
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'main_view' not found. 'main_view' is not a valid view function or pattern name.
Request to /register/ took 0.41 seconds, Method: POST, Status Code: 500
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 19, in post
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 161, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 155, in _create_user
    user.save(using=self._db)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
Request to /register/ took 0.43 seconds, Method: POST, Status Code: 500
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 19, in post
    User.objects.create_user(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 161, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 155, in _create_user
    user.save(using=self._db)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
Request to /register/ took 0.43 seconds, Method: POST, Status Code: 500
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 19, in post
    User.objects.create_user(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 161, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\models.py", line 155, in _create_user
    user.save(using=self._db)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
Request to /register/ took 0.45 seconds, Method: POST, Status Code: 500
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/ took 0.02 seconds, Method: GET, Status Code: 302
Request to /admin/login/ took 0.03 seconds, Method: GET, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.40 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.41 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.41 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.40 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /register/ took 0.40 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/login/ took 0.38 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 200
Request to /admin/ took 0.01 seconds, Method: GET, Status Code: 302
Request to /admin/login/ took 0.03 seconds, Method: GET, Status Code: 200
Request to /admin/login/ took 0.38 seconds, Method: POST, Status Code: 200
Request to /admin/login/ took 0.39 seconds, Method: POST, Status Code: 302
Request to /admin/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/auth/user/ took 0.06 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/auth/user/ took 0.02 seconds, Method: POST, Status Code: 200
Request to /admin/auth/user/ took 0.02 seconds, Method: POST, Status Code: 302
Request to /admin/auth/user/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.38 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/auth/user/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.38 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/auth/user/ took 0.04 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.40 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /logout/
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /logout/
Request to / took 0.01 seconds, Method: GET, Status Code: 200
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.39 seconds, Method: POST, Status Code: 302
Request to / took 0.01 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.39 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'User' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 506, in __get__
    rel_obj = self.related.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'profile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_profile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\user\views.py", line 61, in get
    return render(request, 'user/profile.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 514, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: user_profile
Request to /profile/ took 0.06 seconds, Method: GET, Status Code: 500
Request to /profile/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /cloth/create/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 302
Request to /admin/login/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/login/ took 0.37 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/review/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.05 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.37 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/tag/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/tag/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/tag/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/tag/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.00 seconds, Method: POST, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/category/ took 0.04 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/category/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/category/add/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/category/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/3/change/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/3/change/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/2/change/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/2/change/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/1/change/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /admin/clothes/clothes/1/change/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /admin/clothes/clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /admin/jsi18n/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/s-l1000.jpg took 0.16 seconds, Method: GET, Status Code: 200
Request to /media/1904765_blac_1_26a7ce17-5048-482.jpg took 0.16 seconds, Method: GET, Status Code: 200
Request to /media/Arcteryx-Mens-Atom-SL-Hoody-BLACK-BLACK-Large-L.jpg took 0.17 seconds, Method: GET, Status Code: 200
Request to /clothes/1/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /clothes/1/edit/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /clothes/1/ took 0.01 seconds, Method: POST, Status Code: 302
Request to /clothes/1/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /clothes/1/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/Arcteryx-Mens-Atom-SL-Hoody-BLACK-BLACK-Large-L.jpg took 0.00 seconds, Method: GET, Status Code: 304
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /media/s-l1000.jpg took 0.00 seconds, Method: GET, Status Code: 304
Request to /media/1904765_blac_1_26a7ce17-5048-482.jpg took 0.00 seconds, Method: GET, Status Code: 304
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /logout/ took 0.01 seconds, Method: GET, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /register/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /login/ took 0.38 seconds, Method: POST, Status Code: 302
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/edit/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /profile/edit/
Request to /profile/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /logos/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /logos/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /clothes/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /media/Arcteryx-Mens-Atom-SL-Hoody-BLACK-BLACK-Large-L.jpg took 0.00 seconds, Method: GET, Status Code: 304
Request to /media/1904765_blac_1_26a7ce17-5048-482.jpg took 0.00 seconds, Method: GET, Status Code: 304
Request to /media/s-l1000.jpg took 0.01 seconds, Method: GET, Status Code: 304
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /logos/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /logos/
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to /profile/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.01 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.00 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to / took 0.00 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.00 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
Request to / took 0.01 seconds, Method: GET, Status Code: 200
Request to /profile/ took 0.02 seconds, Method: GET, Status Code: 200
Request to /media/ took 0.01 seconds, Method: GET, Status Code: 404
Not Found: /media/
